### ISSUE TITLE
brainspell.dev does not work

### ISSUE THREAD

**Issue by EmilyVam** [BIDS-collaborative/brainspell#10]
I successfully imported the _brainspell_sanitized.sql_ file into the database, but the **brainspell.dev** still doesn't work. It only displays the Apache 2 Ubuntu Default Page.  
Any suggestion on how to fix this? @jbpoline @r03ert0 @davclark

**Comment by jbpoline** [comment]
@EmilyVam : Are you using Dav virtual machine ?

**Comment by EmilyVam** [comment]
@jbpoline: Yes. I used the Chrome & Firefox browser in the VM, none of them works.

**Comment by jbpoline** [comment]
may be an apache configuration : apache should read the php code of found in [something]/brainspell. 

if I do:  
$grep -R brainspell *
in /etc/apache2 
I get : 
conf-available/brainspell.dev.conf:ServerName brainspell.dev 
conf-enabled/brainspell.dev.conf:ServerName brainspell.dev 
sites-available/brainspell.dev.conf:    DocumentRoot /var/www/html/brainspell
sites-available/brainspell.dev.conf:    ServerName brainspell.dev
sites-enabled/brainspell.dev.conf:  DocumentRoot /var/www/html/brainspell
sites-enabled/brainspell.dev.conf:  ServerName brainspell.dev

(basically the site is available and enabled, and the document root is /var/www/html/brainspell

this will change for your config, but what do you have ?
and in the DocumentRoot directory, you have brainspell code ?

Dav will be more knowledgable than me - but see what you get in you virtual machine ?

**Comment by EmilyVam** [comment]
@jbpoline  Thanks for the reply.

if I do $grep -R brainspell*, I will get:
grep: conf-enabled/base-apache-brainspell.conf: No such file or directory
grep: sites-enabled/apache-site-brainspell.conf: No such file or directory

the only brain spell folder I have in the VM is in the Desktop/Shared/sf_brainspell folder, which is the repo folder shared with my laptop. Would that be the problem?
Because of that, I don't have the brainspell code in the document root directory (/var/www/html). 
Should I copy the brainspell folder into the document root directory?

**Comment by davclark** [comment]
I am pretty sure this means the symbolic links aren't created properly. Can you show the output of `ls -l /etc/apache2/conf-enabled`? Look at the file paths that come after `->`, and my guess is that those are the wrong locations for the files.

My guess is that you made links to the wrong place. In the [wiki](https://github.com/BIDS-collaborative/brainspell/wiki) where I type `<brainspell_git_dir>`, you need to replace that with the actual location of where you have brainspell checked out.

I realized also that shared folders for some reason aren't working quite right for me... so I'd just check brainspell out again (probably in your home directory). But don't worry about this yet!

**Comment by EmilyVam** [comment]
@davclark Thanks for the reply, here is what I tried:
The output of `ls -l /etc/apache2/conf-enabled` is `Desktop/Shared/sf_brainspell/conf/base-apache-brainspell.conf`, this is exactly where I used to `<brainspell_git_dir>`.
From `/etc/apache2/sites-enabled`:
I did `$ sudo ln -s Desktop/Shared/sf_brainspell/conf/apache-site-brainspell.conf .`
From `/etc/apache2/conf-enabled`:
I did `$ sudo ln -s Desktop/Shared/sf_branspell/conf/base-apache-brainspell.conf .`
And the brainspell.dev still does not work, is it because the shared folders simply couldn't work for this? Maybe I should just clone the brainspell repo again in the VM home directory?

**Comment by davclark** [comment]
Yeah! At least I understand the issue... Now let's see if I can explain. 

Those are relative paths to your home directory. So, the full path starts with /home/oski. An example to update:

```
$ sudo ln -sf /home/oski/Desktop/Shared/sf_branspell/conf/base-apache-brainspell.conf .
```

That extra -f means "force" i.e. overwrite the old link. You'll have to update the other links similarly. 

This absolute vs. relative paths understanding is a great piece of learning, and should help the whole team be more effective in unix going forward. JB or I can explain more in person, but you can also google this topic.

**Comment by EmilyVam** [comment]
Thx @davclark, I think I understood what you are talking about. I changed the absolute directory for both site-enabled and cons-enabled, but the brainspell.dev still does not work..... this is so confusing...

**Comment by davclark** [comment]
It seems like it would be worth getting together. Tomorrow is bad for me (and @jbpoline is still out of town), but do you or anyone else have time on Tuesday? I don't think this will take long once we're all sitting together.

Sorry for the confusion!

**Comment by EmilyVam** [comment]
Frank and I are available tomorrow (Tuesday) from 2-330pm. Frank is more familiar with UNIX than I do, so it would be great if three of us can meet together. Thx @davclark

**Comment by anokhikastia** [comment]
Is it possible to meet at 5? I need help uploading the file. I have class from 2-3:30.

**Comment by jbpoline** [comment]
I'm back late afternoon tonight but not sure of the timing yet - probably around 6pm - if you are meeting late today I'll drop by.  

Have others the same problem ?

Things that may be worth trying:
- make sure the myadmin configuration file is correct (I'll send you mine and see what diff tells you)
- see if you can import the file directly into mysql ?  (meaning, is it a myadmin problem, or is it a mysql problem ?)

**Comment by anokhikastia** [comment]
6 is fine for me. Or even sometime Wednesday. I cannot import the file into the mysql database either. Same issue-file too big.
