### ISSUE TITLE
Issue with Blog 

### ISSUE THREAD

**Issue by anokhikastia** [BIDS-collaborative/brainspell#13]
When trying to click on Blog, I get the following error: 
Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /home/oski/brainspell/site/php/brainspell.php on line 330
Warning: file_get_contents(http://brainspell.org/php/blog.php): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /home/oski/brainspell/site/php/brainspell.php on line 330

Line 330: 
$blog=file_get_contents("http://brainspell.org/php/blog.php");

I haven't modified anything. When I switch to someone else's branch, I still get that error. Is something wrong with just my computer or there is an actual error in accessing this file?

**Comment by jbpoline** [comment]
I don't have the problem,  Do you get an error if you go to http://brainspell.org/php/blog.php ?

**Comment by r03ert0** [comment]
the blog link is just a link to a php script that takes from my blog
(wordpress) only the posts tagged brainspell. There is some general
information about updates, and a couple of videos (but overall, i don't
post as often as i should...).

is there anything in particular you would like to do with the blog code, or
you were just checking the links?

cheers,
roberto

**Comment by anokhikastia** [comment]
it's working now. didn't change anything.
