### ISSUE TITLE
10/29 Meeting Notes & Next Steps

### ISSUE THREAD

**Issue by EmilyVam** [BIDS-collaborative/brainspell#15]
### Notes
- **Variable vs. Comment**: Clarified the code regarding to the `<!-- Bla Bla Bla -->` symbol, more detail explanations in the [Documentation.md](https://github.com/BIDS-collaborative/brainspell/blob/BIDS-collaborative/Documentation.md) file.
- **Text Search**: To find the filename with certain text using command line:  `grep -lr "any text" *`
### Next Steps
- [x] Modify all the code to follow the _Variable vs. Comment_ convention.
- [x] Continue to implement the article title snapshot with the button feature indicated in issue #12 .
- [x] Attend the code structure meeting on Tuesday Nov. 3rd at 5pm in the BIDS

_P.S. Please feel free to add more notes @anokhikastia. To avoid redundant work, please comment below if you complete any of them._ @anokhikastia @SydneyHuang

**Comment by davclark** [comment]
Great to see meeting notes!
