### ISSUE TITLE
Get going with Docker Machine

### ISSUE THREAD

**Issue by davclark** [BIDS-collaborative/brainspell#22]
I'm trusting @stefanv can keep things straight, so putting this here prior to settling on the final development location... I'll keep notes below.

**Comment by davclark** [comment]
I installed via homebrew. Kitematic is available via brew cask, installed docker, docker-machine, and docker-compose via regular homebrew.

Immediately hit rate limiting trying `docker-machine create --driver virtualbox default`. Docs on how to give docker-machine this token are hard to find.

**Comment by davclark** [comment]
The secret is to create a public access GitHub API token and assign it to the `MACHINE_GITHUB_API_TOKEN` shell var.

**Comment by jbpoline** [comment]
Dav: do you recommend folks on mac (OSX) to try to play with this ? or to wait till Friday ?

**Comment by davclark** [comment]
I think it's good for them to try.

Also, here are a useful alias & function I've set up:

``` sh
alias dm=docker-machine

# simple functions to allow arguments inside of complicated commands
dmenv () {
    eval "$(docker-machine env $1)"
}
```
