### ISSUE TITLE
Cannot upload file 

### ISSUE THREAD

**Issue by anokhikastia** [BIDS-collaborative/brainspell#7]
I cannot upload the file into myphpadmin because it says that the file is too large. How do I go about fixing this? Thanks! @jbpoline @davclark

**Comment by EmilyVam** [comment]
Same issue here

**Comment by EmilyVam** [comment]
Thanks to @hny221 , I guess that is because we couldn't modify the initial file with the upload_max_filesize variable, so it should be resolved after we get the super user password with issue #8 
@jbpoline @davclark @r03ert0 

**Update**: super user password is _oski_

**Comment by davclark** [comment]
As we figure these things out, can we move the info to the wiki or instructions, and close the issues?
