### ISSUE TITLE
Configuring apache 

### ISSUE THREAD

**Issue by anokhikastia** [BIDS-collaborative/brainspell#9]
While configuring apache, when we type in the 1st command, we get: 
ln: failed to create symbol link ' ./headers.load' : Read only file system

How do we fix this?

**Comment by EmilyVam** [comment]
Hey @anokhikastia , I figured this out!
First you have to modify the /etc/hosts file by adding "127.0.0.1    brainspell.dev"  line. 
Then, before you typ "sudo ln ....", make sure you are in the /etc/apache2/mods-enabled directory.

P.S. I also figured out how to paste the command line you copied from your laptop, try shift + control + v!

**Comment by davclark** [comment]
If you forget the key-chord to do copy-cut-paste in the BCE / Ubuntu terminal, you can always look under the edit menu. Because the control key is often used by unix command-line apps, they added this extra "shift" to the key command.

**Comment by anokhikastia** [comment]
I was able to configure apache and I also changed the variables in the php file to 64M but I am still unable to upload the brainspell_sanitized.sql file to the database. It is still giving me the same error saying that it cannot upload such a big file.

**Comment by jbpoline** [comment]
Hi  Anokhi

Here's my php.ini file (in the /etc/php5/apache2 on my system - not sure
where it is on your VM)
just to check that you have the same settings for the 64M (2 variables)

cheers
JB

**Comment by anokhikastia** [comment]
Could it be that the ini file and the .sql file are in some way not connected to each other? My php.ini file is located in the /etc/php5/apache2.

**Comment by davclark** [comment]
When you edit files, the program needs to re-read them. The easiest thing is to do a reboot - in which case all config files are re-loaded.

**Comment by anokhikastia** [comment]
I rebooted and things got worse. I can't even open the the phpmyadmin now.

**Comment by davclark** [comment]
Hmm... it may be easier to sit down with me or one of your team-mates. Let's shoot for that as soon as we can?
